rapsys_air_homepage:
    path: /
    controller: Rapsys\AirBundle\Controller\DefaultController::index
    methods: GET

rapsys_air_contact:
    path: /contact
    controller: Rapsys\AirBundle\Controller\DefaultController::contact
    methods: GET|POST

rapsys_air_admin:
    path: /admin
    controller: Rapsys\AirBundle\Controller\DefaultController::admin
    methods: GET

rapsys_air_session:
    path:     /admin/session/{id}
    controller: Rapsys\AirBundle\Controller\DefaultController::session
    requirements:
        id: '\d+'
    methods: GET
