rapsys_air_homepage:
    path:     /
    defaults: { _controller: RapsysAirBundle:Default:index }

rapsys_air_admin:
    path:     /admin
    defaults: { _controller: RapsysAirBundle:Default:admin }

rapsys_air_contact:
    path:     /contact
    defaults: { _controller: RapsysAirBundle:Default:contact }

rapsys_air_session:
    path:     /admin/session/{id}
    defaults: { _controller: RapsysAirBundle:Default:session }
    requirements:
        id: '\d+'
